name: Auto link PR to Issues

on:
  pull_request:
    types: [opened, edited, synchronize, closed]

jobs:
  call-linker:
    uses: inji/.github/.github/workflows/pr-linker.yml@main
    secrets:
      CROSS_REPO_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
